name: VelaUX Migrator Test

on:
  push:
    branches:
      - main
      - release-*
    tags:
      - v*
  workflow_dispatch: { }
  pull_request:
    branches:
      - main
      - release-*

env:
  # Common versions
  GO_VERSION: '1.19'

permissions:
  contents: read

jobs:
  unit-tests:
    runs-on: ubuntu-20.04
    steps:
      - name: Set up Go
        uses: actions/setup-go@6edd4406fa81c3da01a34fa6f6343087c207a568
        with:
          go-version: ${{ env.GO_VERSION }}
        id: go

      - name: Check out code into the Go module directory
        uses: actions/checkout@ac593985615ec2ede58e132d2e21d2b1cbd6127c
        with:
          submodules: true

      - name: Cache Go Dependencies
        uses: actions/cache@6998d139ddd3e68c71e9e398d8e40b71a2f39812
        with:
          path: .work/pkg
          key: ${{ runner.os }}-pkg-${{ hashFiles('**/go.sum') }}
          restore-keys: ${{ runner.os }}-pkg-

      - name: Install ginkgo
        run: |
          sudo sed -i 's/azure\.//' /etc/apt/sources.list
          sudo apt-get update
          sudo apt-get install -y golang-ginkgo-dev

      - name : Set up MySQL
        uses: mirromutth/mysql-action@v1.1
        with:
          mysql database: 'kubevela'
          mysql root password: 'kubevelaSQL123'

      - name: Set up MongoDB
        uses: supercharge/mongodb-github-action@d26215f71b2ce60420a2a3776a25893d11a65f85 # 1.9.0
        with:
          mongodb-version: '5.0'

      - name: install Kubebuilder
        uses: RyanSiu1995/kubebuilder-action@ff52bff1bae252239223476e5ab0d71d6ba02343
        with:
          version: 3.1.0
          kubebuilderOnly: false
          kubernetesVersion: v1.21.2

      - name: Run unit test
        run: make unit-test
