name: Release

on:
  push:
    tags:
      - "v*"
  workflow_dispatch: { }

permissions:
  contents: read

jobs:
  build:
    runs-on: ubuntu-22.04
    name: goreleaser
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - run: git fetch --force --tags
      - name: Set up Go
        uses: actions/setup-go@v4
        with:
          go-version: 1.19
          cache: true
      - uses: goreleaser/goreleaser-action@v4
        with:
          distribution: goreleaser
          version: latest
          args: release --clean --timeout 30m
          workdir: ./cmd
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}